website/auth.py
from sqlite3 import IntegrityError
from flask import Blueprint, redirect, render_template, request, flash, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from sqlalchemy.exc import IntegrityError
from .models import Favorites, Users, Posts
from werkzeug.security import generate_password_hash, check_password_hash
from . import db, s3, BUCKET_NAME


auth = Blueprint('auth', __name__)


@auth.route('/', methods=['GET', 'POST'])
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.home', user=current_user))

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = Users.query.filter_by(email=email).first()
        
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in successfully!", category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home', user=current_user))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('No account with that email has been created', category='error')
    return render_template('login.html', user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if current_user.is_authenticated:
        return redirect(url_for('views.home', user=current_user))

    if request.method == "POST":
        first_name = request.form.get('firstName')
        last_name = request.form.get('lastName')
        username = request.form.get('username')
        email = request.form.get('email')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        user = Users.query.filter_by(email=email).first()

        if user:
            flash('An account with this email already exists, try again.', category='error')
        if len(email) < 3:
            flash('Your email needs to contain at least 3 characters, please try again.', category='error')
        elif len(first_name) < 1:
            flash('Your first name needs to contain more than 1 character, please try again.', category='error')
        elif len(last_name) < 1:
            flash('Your last name needs to contain more than 1 character, please try again.', category='error')
        elif len(username) < 4:
            flash('Your username needs to contain more than 3 character, please try again.', category='error')
        elif password1 != password2:
            flash('Passwords do not match, please try again.', category='error')
        elif len(password1) < 7:
            flash('Your password needs to contain at least 7 characters, try again.', category='error')
        else:
            new_user = Users(first_name=first_name, last_name=last_name, username=username, email=email, password=password1)
            print(new_user)
            db.session.add(new_user)
            try:
                db.session.commit()
            except IntegrityError as e:
                db.session.rollback()
                flash('Username already taken, try again.', category='error')
                return redirect(url_for('auth.sign_up'))
            flash('Account created!', category='success')
            this_user = Users.query.filter_by(email=email).first()
            login_user(this_user, remember=True)
            return redirect(url_for('views.home', user=current_user))

    return render_template('sign_up.html', user=current_user)

@auth.route('/profile', methods=['GET', 'POST'])
def profile():
    
    user = Users.query.filter_by(username=current_user.username).first()
    users_posts = Posts.query.filter_by(post_author=user.user_id).all()
    users_favorites = Favorites.query.filter_by(user_id=user.user_id).all()
    favorite_ids = [x.post_id for x in users_favorites]
    fav_posts = Posts.query.filter(Posts.post_id.in_(favorite_ids)).all()

    if request.method == 'POST':

        update = request.form.get('cpassword')
        newpass = request.form.get('newPassword')
        confirmpass = request.form.get('confirmPassword')

        if update:
            if check_password_hash(user.password, update):
                if len(newpass) < 7:
                    flash('Your password needs to contain at least 7 characters, try again.', category='error')
                    return redirect(url_for('auth.profile', user=current_user))
                if newpass != confirmpass:
                    flash('The two new password fields must match. Please try again.')
                    return redirect(url_for('auth.profile', user=current_user))
                user.password = generate_password_hash(password=confirmpass, method="sha256")
                db.session.commit()
                flash('Password changed successfully!', category='success')
            else:
                flash('The current password you entered is incorrect. Please try again.')

        see_more = request.form.get('seeMore')
        if see_more:
            return redirect(url_for('views.single_post', user=current_user, id = see_more))

        remove_post = request.form.get('removePost')
        if remove_post:
            selected = Posts.query.filter_by(post_id=remove_post).first()
            db.session.delete(selected)
            db.session.commit()

            users_posts = Posts.query.filter_by(post_author=user.user_id).all()
            users_favorites = Favorites.query.filter_by(user_id=user.user_id).all()
            favorite_ids = [x.post_id for x in users_favorites]
            fav_posts = Posts.query.filter(Posts.post_id.in_(favorite_ids)).all()

            s3.delete_object(Bucket=BUCKET_NAME,Key=selected.post_image)

            flash('Post deemed not worthy of existing. It has been removed.')
            return render_template('profile.html', user=current_user, posts=users_posts, favorites=fav_posts)

    return render_template('profile.html', user=current_user, posts=users_posts, favorites=fav_posts)

website/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
import random
from .models import Posts, Favorites
from . import db, s3, BUCKET_NAME


views = Blueprint('views', __name__)


@views.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        text = request.form.get('post_content')
        title = request.form.get('post_title')

        post_img = request.files['p_image']
        filename = secure_filename(post_img.filename)

        if post_img:
            s3.upload_fileobj(
                Bucket = BUCKET_NAME,
                Fileobj = post_img,
                Key = filename
            )

        if len(title) <1:
            flash('Please enter a title', category='error')
        if len(text) < 1:
            flash('No text entered, try again.', category='error')
        else:
            user_text = Posts(post_title=title, post_content=text, post_image=filename, post_author=current_user.user_id)
            db.session.add(user_text)
            db.session.commit()
            flash("Thanks for sharing!")
    return render_template('home.html', user=current_user)

@views.route('/feed', methods=['GET', 'POST'])
@login_required
def feed():
    if request.method == 'POST':
        see_more = request.form.get('seeMore')
        if see_more:
            return redirect(url_for('views.single_post', user=current_user, id = see_more))
        postNum = request.form.get('favbtn')
        newFav = Favorites(user_id=current_user.user_id, post_id=postNum)
        exists = Favorites.query.filter_by(user_id=current_user.user_id, post_id=postNum).first()
        if exists:
            flash('This post is already a favorite!', category='error')
        else:
            db.session.add(newFav)
            db.session.commit()
            flash('Added to favorites!', category='success')

    all_posts = db.session.query(Posts).all()
    def shuffle_posts(posts):
        try:
            result = list(posts)
            random.shuffle(result)
            return result
        except:
            return posts

    return render_template('feed.html', user=current_user, all_posts=shuffle_posts(all_posts))

@views.route('/posts', methods=['GET', 'POST'])
def single_post():
    if request.method == 'POST':
        if current_user.is_anonymous:
            flash('Please make an account or log in to add as favorite', category='error')
            postNumber = request.args.get('id')
            this_post = Posts.query.filter_by(post_id=postNumber).first()
            return render_template('single_post.html', user=current_user, post=this_post, bktname=BUCKET_NAME)
        postNum = request.form.get('favbtn')
        newFav = Favorites(user_id=current_user.user_id, post_id=postNum)
        exists = Favorites.query.filter_by(user_id=current_user.user_id, post_id=postNum).first()
        if exists:
            flash('This post is already a favorite!', category='error')
        else:
            db.session.add(newFav)
            db.session.commit()
            flash('Added to favorites!', category='success')
    postNumber = request.args.get('id')
    this_post = Posts.query.filter_by(post_id=postNumber).first()
    return render_template('single_post.html', user=current_user, post=this_post, bktname=BUCKET_NAME)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {{ share.load() }}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />   
    <link rel="icon" href="static/logo.png">
    <link rel="stylesheet" href="{{ url_for('static', filename='base_css.css') }}">
    {% block style%}
    {% endblock %}
    <title>{% block title%}base{% endblock %}</title>

</head>
<body>
    <nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
        {% if user.is_authenticated %}
            <img  id="navLogo" src="static/nav_logo.png" class="rounded-square navbar-brand img-fluid">
        {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class ="collapse navbar-collapse" id="navbar">
            <div class ="navbar-nav d-flex flex-row justify-content-around">
                {% if user.is_authenticated %}
                    <a id = "home" href={{ url_for('views.home') }} class="nav-item nav-link">Secret</a>
                    <a id = "home" href={{ url_for('views.feed') }} class="nav-item nav-link">Feed</a>
                    <a id = "logout" href={{ url_for('auth.logout') }} class="nav-item nav-link">Logout</a>
                {% else %}
                <a id = "login" href={{ url_for('auth.login') }} class="nav-item nav-link">Login</a>
                <a id = "signUp" href={{ url_for('auth.sign_up') }} class="nav-item nav-link">Sign Up</a>
                {% endif %}
            </div>
        </div>
        {% if user.is_authenticated %}
        <a id="welcome" class="nav-item nav-link ml-auto" href={{ url_for('auth.profile') }}>Welcome, {{ user.username }}</a>
        {% endif %}
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                <div class="alert alert-danger alert-dismissaable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% else %}
                <div class="alert alert-success alert-dismissaable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="container">
        {% block body%}
        {%endblock%}
    </div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

website/templates/feed.html
{% extends 'base.html'%}

{% block style%}
<link rel="stylesheet" href="{{ url_for('static', filename='feed_css.css') }} ">
{% endblock %}


{% block title%}Feed{% endblock %}


{% block body%}

    {% for post in all_posts %}
    <div align="center">
        <div class="card shadow p-3 mb-5 bg-white rounded postBG">
            <div class="card-body text-center" align="left">
                <h4 class="card-title">{{ post.post_title }}</h4>
                <h5 class="card-subtitle mb-2 text-muted">{{ post.post_date.strftime('%m-%d-%Y') }}</h5>
                <p class="card-text">{{ post.post_content }}</p>
                <form method="post">
                    <div class="d-flex justify-content-around">
                        <button name="favbtn" value = {{ post.post_id }} class="btn btn-white btn-xs">Favorite <i class="fa-solid fa-heart"></i></button>
                        <button name="seeMore" class="btn btn-white btn-xs" value={{ post.post_id }}>See More <i class="fa-solid fa-angles-right"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}

{% endblock %}

website/templates/home.html
{% extends 'base.html' %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='home_css.css') }}">
{% endblock %}

{% block title%}Home{% endblock %}

{% block body%}
<div align="center">
    <h1 id="headline">share a secret!</h1>
    <h2 id="notice">all posts are anonymous, but be mindful that all text and images uploaded are 100% public</h2>
</div>
<form method="POST" enctype="multipart/form-data">
    <div class="d-flex flex-direction-column justify-content-around">
        <div>
            <div align="center" class="mb-3">
                <input type="text" name="post_title" id="post_title" placeholder="Title your secret">
            </div>
            <div align="center">
                <textarea name="post_content" id="post_content" cols="90" rows="10" placeholder='e.g. "The time I was most embarrassed was..."'></textarea>
            </div>
            <div align="center" class="mt-3">
                <h3>have an image to add with your secret?</h3>
                <i class="fa-solid fa-photo-film imgreel"></i>
                <input type="file" name='p_image'>
            </div>
            <div align="center" class="mt-3">
                <button type="submit" class="btn btn-primary">Share</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

website/templates/login.html
{% extends 'base.html' %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='logo_css.css') }}">
{% endblock %}

{% block title%}Login{% endblock %}

{% block body%}
<div class="d-flex flex-column align-items-center">
    <img class="img-fluid mb-3 mt-4"src="static/logo.png" alt="seqret logo">
    <form method="POST">
        <h3 align="center">Login</h3>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
        </div>
        <h5 align="center">Don't have an account? Sign up <a href={{ url_for('auth.sign_up') }}>here</a></h5>
        <div align="center">
            <button class="btn btn-dark" type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

website/templates/profile.html
{% extends 'base.html' %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='profile_css.css') }}">
{% endblock %}

{% block title %}
Profile
{% endblock %}


{% block body%}
<ul class="nav nav-tabs d-flex flex-row justify-content-around mt-3">
    <li class="active"><a data-toggle="tab" href="#myProfile" class="profileTab">Profile</a></li>
    <li><a data-toggle="tab" href="#myFavs" class="profileTab">Favorites</a></li>
    <li class="active"><a data-toggle="tab" href="#myPosts" class="profileTab">Posts</a></li>
</ul>
<div class="tab-content">
    <div id="myProfile" class="tab-pane fade show active">
        <div class="card shadow p-3 mb-5 bg-white rounded postBG">
            <div class="card-body" align="center">
                <form method="post">
                    <h4>Update password</h4>
                    <div class="form-group">
                        <label for="cpassword">Current password:</label>
                        <input type="password" class="form-control" id="cpassword" name="cpassword" placeholder="Enter current password">
                    </div>
                    <div class="form-group">
                        <label for="newPassword">New password:</label>
                        <input type="password" class="form-control" id="cpassword" name="newPassword" placeholder="Enter new password">
                    </div>
                    <div class="form-group">
                        <label for="confirmPassword">Confirm new password:</label>
                        <input type="password" class="form-control" id="cpassword" name="confirmPassword" placeholder="Enter new password">
                    </div>
                    <button class="btn btn-dark" name="updatePass" type="submit">Update</button>
                </form>
                </div>
            </div>
        </div>
            <div id="myPosts" class="tab-pane fade">
                {% for post in posts %}
        <div align="left">
            <div class="card shadow p-3 mb-5 bg-white rounded postBG">
                <div class="card-body" align="center">
                    <h4 class="card-title">{{ post.post_title }}</h4>
                    <h5 class="card-subtitle mb-2 text-muted">{{ post.post_date.strftime('%m-%d-%Y') }}</h5>
                    <p class="card-text">{{ post.post_content }}</p>
                    <form method="post">
                        <div class="d-flex justify-content-around">
                            <button name="seeMore" class="btn btn-white btn-xs" value={{ post.post_id }}>See More <i class="fa-solid fa-angles-right"></i></button>
                            <button name="removePost" class="btn btn-white btn-xs" value={{ post.post_id }}>Delete Post <i class="fa-solid fa-skull"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div id="myFavs" class="tab-pane fade">
        {% for favorite in favorites %}
        <div align="left">
            <div class="card shadow p-3 mb-5 bg-white rounded postBG">
                <div class="card-body" align="center">
                    <h4 class="card-title">{{ favorite.post_title }}</h4>
                    <h5 class="card-subtitle mb-2 text-muted">{{ favorite.post_date.strftime('%m-%d-%Y') }}</h5>
                    <p class="card-text">{{ favorite.post_content }}</p>
                    <form method="post">
                        <div class="d-flex justify-content-around">
                            <button name="seeMore" class="btn btn-white btn-xs" value={{ favorite.post_id }}>See More <i class="fa-solid fa-angles-right"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{%endblock%}

website/templates/sign_up.html
{% extends 'base.html' %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='sign_up_css.css') }}">
{% endblock %}

{% block title%}Home{% endblock %}

{% block body%}
<div class="d-flex flex-row align-items-center justify-content-around">
<img class="img-fluid mb-4"src="static/logo.png" alt="seqret logo">
    <form method="POST" class="mt-3">
        <h3 align="center">Sign Up</h3>
        <div class="form-group">
            <label for="firstName">First Name:</label>
            <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter first name">
        </div>
        <div class="form-group">
            <label for="lastName">Last Name:</label>
            <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Enter last name">
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
        </div>
        <div class="form-group">
            <label for="password1">Password:</label>
            <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password">
        </div>
        <div class="form-group">
            <label for="password2">Confirm password:</label>
            <input type="password" class="form-control" id="password2" name="password2" placeholder="Enter password">
        </div>
        <h5 align="center">Already have an account? Sign in <a href={{ url_for('auth.login') }}>here</a></h5>
        <br>
        <div align="center">
            <button class="btn btn-dark" type="submit">Submit</button>
        </div>
    </form>
</div>

{% endblock %}

website/templates/single_post.html
{% extends 'base.html' %}


{% block style%}
<link rel="stylesheet" href="{{ url_for('static', filename='post_css.css') }}">
{%endblock%}

{% block title %}
    {{ post.post_title }}
{%endblock%}

{% block body %}


<div align="center" class="mt-4">
    <div class="card shadow p-3 mb-5 bg-white rounded postBG">
        <div class="card-body text-center" align="left">
            <h4 class="card-title">{{ post.post_title }}</h4>
            <h5 class="card-subtitle mb-2 text-muted">{{ post.post_date.strftime('%m-%d-%Y') }}</h5>
            <p class="card-text">{{ post.post_content }}</p>
            <div id = "postcard" class="d-flex justify-content-around">
                <form method="post">
                    <button name="favbtn" value = {{ post.post_id }} class="btn btn-white btn-xs">Favorite <i class="fa-solid fa-heart"></i></button>
                </form>
                    <a href="#thisqrcode">
                        <button name="showQR" class="btn btn-white btn-xs" data-toggle="collapse" data-target="#thisqrcode" aria-expanded="false" aria-controls="thisqrcode" value={{ post.post_id }}>Show QR <i class="fa-solid fa-angles-down"></i></button>
                    </a>
                    <button name="showIMG" class="btn btn-white btn-xs" data-toggle="collapse" data-target="#thisimage" aria-expanded="false" aria-controls="thisimage" value={{ post.post_id }}>Show Image <i class="fa-solid fa-angles-down"></i></button>
                </div>
                <div class="collapse mt-5" id="thisimage">
                    {% if post.post_image %}
                    <img class="img-fluid" src="https://{{ bktname }}.s3.amazonaws.com/{{ post.post_image }}" alt="{{ post.post_image }}">
                    {% else %}
                    <h5>No image attached to this post :(</h5>
                    {% endif %}
                </div>
                <div class="collapse mt-5" id="thisqrcode">
                    <img class="img-fluid" src="{{ qrcode( request.url, box_size=5, error_correction='H', back_color='#383F51', fill_color='#ccc', icon_img='../static/logo3.png') }}" alt="qrcode">
                    <div class="social-share mt-5" data-sites="facebook, twitter, linkedin" data-mobile-sites="weibo, douban, qq, qzone" align="center"></div>
            </div>
    </div>
</div>
{% endblock %}